language: node_js

node_js:
  - "stable"

sudo: false

env:
  - CLIENT_URL="/openeo-processes-docgen/demo/"

script:
  - npm run build
  - rm -rf page
  - mkdir -p page
  - mv dist page/demo
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: page
  committer-from-gh: true
  keep-history: true
  on:
    branch: master
